"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Serachfooter from "@/components/Serachfooter";
import {usePathname} from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-600 text-gray-800`}
      >
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1 w-full max-w-[100vw] mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 bg-gray-400">
            {children}
          </main>
          {pathname === "/search" ? <Serachfooter /> : <Footer />}
        </div>
      </body>
    </html>
  );
}
